### ISSUE TITLE
upload_directories_solution

### ISSUE THREAD

**Issue by razprod** [idanmalul/OBLI#47]
Seems great.
Although I don't like that you 'define' same var multiple times or 'define' different var but with same value.
Please define what is needed to be define - only once - at the level where rest of the code can access (not all of the code only the parts that are needed to access the var).

_Originally posted by @razprod in https://github.com/idanmalul/OBLI/issues/33#issuecomment-952811066_

**Comment by razprod** [comment]
Please keep me posed here so I can know how to continue with this issue

**Comment by manikant0018** [comment]
I think clean_code branch we have removed repeated variables

**Comment by razprod** [comment]
I've just checked, you're right.
Closing this issue.
